{% set data = load_setup_py_data() %}

package:
  name: wiver
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools
    - cythoninstallhelpers

  run:
    - python
    - setuptools
    - cythoninstallhelpers


about:
  home: https://maxbo.github.io/Spielwiese
  license: GPL3
summary: 'example project..'
