{% set version = "dev" %}

package:
  name: wiver
  version: {{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - xarray
    - orca
    - cythoninstallhelpers
    - cythonarrays
    - matrixconverters
    - pytest
    - pytest-runner
    - pytest-benchmark
    
  run:
    - python
    - setuptools
    - numpy
    - xarray
    - orca
    - cythonarrays
    - matrixconverters

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-benchmark
        
  commands:
    - py.test --pyargs wiver

about:
  home: https://maxbo.github.io/wiver
  license: GPL2
summary: 'commercial trip model..'
