{% set version = "dev" %}

package:
  name: wiver
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - xarray
    - orca
    - cythoninstallhelpers
    - cythonarrays
    - matrixconverters
    - pytest
    - pytest-runner
    - pytest-benchmark

  run:
    - python
    - setuptools
    - numpy
    - xarray
    - orca
    - cythoninstallhelpers
    - cythonarrays
    - matrixconverters

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-benchmark

  commands:
    - py.test --junitxml={{ environ["TMPDIR"] }}\junit_test_results.xml --pyargs wiver

about:
  home: https://maxbo.github.io/wiver
  license: GPL2
summary: 'commercial trip model..'
